### ISSUE TITLE
Rowan berries doesnt look like food

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/SpiceOfLife#6]
Rowan berries from witchery has no tooltip about eaten or not yet eaten and also has no tooltip about diminishing returns.

**Comment by mitchej123** [comment]
Witchery.... it doesn't do many things standard.  Going to pass on this one.

**Comment by Impos913** [comment]
Heh ok

**Comment by draknyte1** [comment]
Report it on WitcheryExtras, easy fix.

**Comment by mitchej123** [comment]
https://github.com/squeek502/AppleCore/wiki/Integrating-food-items-with-AppleCore

**Comment by draknyte1** [comment]
Still technically a Witchery problem, so am happy to fix it on my side.

**Comment by mitchej123** [comment]
Oh I agree, I was just pointing out how to make it work with Spice of Life (indirectly via AppleCore).  I took a look at the decompiled code and it's using a custom onEaten method for all of it's items, and doing an if(rowanBerry) to manually apply the food/saturation -- which is why it's bypassing AppleCore.
